#!/bin/sh
[ $# -eq 0 ] && { echo "Usage: $0 domain [rs]"; exit 1; }

ipset_add_file="/etc/storage/dnsmasq/custom/gfwlist_add.cfg"
ipset_gfwlist_file="/etc/storage/dnsmasq/custom/gfwlist.cfg"

if [ -n "$1" ]; then
    check_dup=`grep "ipset=/$1" $ipset_add_file`
    check_dup_g=$(grep "ipset=/$1" $ipset_gfwlist_file)
fi

if [ -n "$check_dup" ]; then
    sed -i -e "/ipset=\/$1/d" $ipset_add_file
    echo "$1 delete from $ipset_add_file"
    ipset -F gfwlist
elif [ -n "$check_dup_g" ]; then
    sed -i -e "/ipset=\/$1/d" $ipset_gfwfile_file
    echo "$1 delete from $ipset_gfwlist_file"
    ipset -F gfwlist
else
    echo "$1 not found in gfwlist file!"
fi

if [ -n "$2" ]; then
    echo "Restarting dnsmasq..."
    killall dnsmasq
    dnsmasq
    restart_dns
fi
