#!/bin/sh
BIN=pdnsd
BINPATH="/opt/sbin/"
CONF="-c /opt/etc/pdnsd.conf"
CACHEPATH="/opt/var/cache/pdnsd"
CACHEFILE="${CACHEPATH}/pdnsd.cache"
PID_F="/opt/var/run/$BIN.pid"
alias elog="logger -t $BIN -s"
COND=$1
[ $# -eq 0 ] && COND="start"

case $COND in
stop)
    elog "Stopping $BIN... "
    [ -n "`pidof $BIN`" ] && { kill -15 `pidof $BIN`; rm $PID_F; }
    elog "$BIN Stopped. "
    ;;
start)
    elog "Starting $BIN... "
    if [ -n "`pidof $BIN`" ]
    then
        elog "$BIN already running."
    else
        [ ! -d $CACHEPATH ] && { mkdir -p $CACHEPATH; chmod 777 $CACHEPATH; }
        ${BINPATH}${BIN}
        [ "$?" = "0" ] && elog "$BIN start success. " || elog "$BIN start failed. "
    fi
  ;;
restart)
    elog "Restarting $BIN... "
    ct=0
    while [ $ct -ne 2 ]
    do
        [ -n "`pidof $BIN`" ] && { kill -15 `pidof $BIN`; rm $PID_F; }
        [ ! -d $CACHEPATH ] && { mkdir -p $CACHEPATH; chmod 777 $CACHEPATH; }
        sleep 1
        ${BINPATH}${BIN}
        sleep 1
        ct=`netstat -ln | grep "5454" | wc -l`
    done
    [ -n "`pidof $BIN`" ] && elog "$BIN Restart Success. " || elog "$BIN Restart failed"
    ;;
*)
    elog "Usage: $0 (start|stop|restart)"
    exit 1
esac