#!/bin/sh
alias elog="logger -t $BIN -s"
###这里编辑你的账号信息
UDOMAIN="someone@xmail.com@ssh.wendangku.org"   #SSH服务器域名及用户名
UPORT="8443"                                    #SSH服务器端口
UPASSWD="abc3344567abc"                            #SSH服务器登陆密码
OBKEY="bluessh"               #Obfuscate SSH混淆码,普通SSH请设为""空值

###以下不懂的请不要动
BIN=ssh_ofc
BINPATH="/opt/etc/obssh/bin/"
LIPPORT="127.0.0.1:7171"
PID_F="/var/run/$BIN.pid"
SSHOPT="-o ServerAliveInterval=30 -o ServerAliveCountMax=2 -o StrictHostKeyChecking=no -NfnT"

if [ -n "$OBKEY" ]; then
    CONF="$SSHOPT -Z ${OBKEY} -p ${UPORT} ${UDOMAIN} -D ${LIPPORT}"
else
    CONF="$SSHOPT -p ${UPORT} ${UDOMAIN} -D ${LIPPORT}"
fi

alias elog="logger -t $BIN -s"

start_os() {
    elog "Starting $BIN... "
    if [ -n "`pidof $BIN`" ]; then
        elog "${BIN} already running!"
    else
        sshpass -p ${UPASSWD} ${BINPATH}${BIN} $CONF > /dev/null 2>&1 &
        if [ "$?" = "0" ]; then
			elog "$BIN start success. "
			echo $(pidof sshpass) > $PID_F
			echo $(pidof ssh_ofc) >> $PID_F
		else
			elog "$BIN start failed. "
		fi
    fi
}

stop_os() {
    elog "Stopping $BIN... "
    [ -n "`pidof $BIN`" ] && { killall $BIN; rm $PID_F; }
    [ -n "`pidof sshpass`" ] && killall sshpass
    elog "$BIN Stopped. "
}

restart_os() {
    elog "Restarting $BIN... "
    stop_os
    sleep 1
    start_os
    elog "$BIN Restart Success. "
}

COND=$1
[ $# -eq 0 ] && COND="start"
case $COND in
stop)
    stop_os
  ;;
start)
    start_os
  ;;
restart)
    restart_os
  ;;
watchdog)
    ct=`netstat -ln | grep "7171" | wc -l`
    while [ $ct -ne 1 ]
    do
        elog "$BIN stopped abnormal, try to restart it..."
        restart_os
        sleep 5
        ct=`netstat -ln | grep "7171" | wc -l`
    done
  ;;
*)
  elog "Usage: $0 (start|stop|restart|watchdog)"
  exit 1
esac